config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  #temporary testing route -- delete later
  get '/mobile', to: 'pages#mobile'
  get '/desktop', to: 'pages#desktop'

  # dashboard for employer
  namespace :employer do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    get '/show', to: 'users#show', as: :show
    get '/employees', to: 'users#index', as: :index
  end

  # dashboard for employee
  namespace :employee do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    get '/show', to: 'users#show', as: :show
  end

  resources :receipts, only: :show do
    resources :receipt_items, only: [:new, :create]
  end
  resources :trips do
    get '/export', to: 'trips#export', as: :export
    resources :receipts, only: [:new, :update, :create]
  end
  resources :receipts, only: [:show, :edit, :destroy] do
    resources :receipt_items, except: [:index, :show, :destroy, :edit]
  end
  resources :receipt_items, only: [:destroy, :edit]
  get '/users/:id', to: 'users#show', as: :user_show

  #pdf generating routes
  get '/trips/:id/report', to: 'trips#report', as: :report
end

app/controllers/employee/users_controller.rb
module Employee
  class UsersController < ApplicationController

    def dashboard
      @user = current_user
      @current_trip = @user.trips.order(start_date: :desc).first
      @query = params[:query]
      authorize @user
      if params[:query].present?
        @trips = Trip.search_all(params[:query])
      else
        @trips = @user.trips.order(start_date: :desc)
      end
    end

    def show
      @user = User.find_by(id: params[:id])
      authorize @user
    end

  end
end

app/views/employee/dashboard.html.erb
<!-- <%#= render 'shared/side-bar' %> -->

Welcome
<p><%= @user.first_name %></p>
<p><%= @user.last_name %></p>
<h1>Your list of trips</h1>
<div class="landing-arguments-container">
  <div class="argument">
    <div class="argument-info">
      <% @user.trips.each do |trip| %>
        <p><strong><%= link_to trip.name, trip_path(trip)%></strong></p>
        <p><%=  trip.destination %></p>
        <p><%=  trip.purpose %></p>
        <p> Budget = 55000 yens </p>
      <% end %>
    </div>
  </div>
</div>
<%= link_to "Create a new trip", new_trip_path, class: "btn btn-approve w-30"  %>