config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  #temporary testing route -- delete later
  get '/mobile', to: 'pages#mobile'
  get '/desktop', to: 'pages#desktop'

  # dashboard for employer
  namespace :employer do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    get '/show', to: 'users#show', as: :show
    get '/employees', to: 'users#index', as: :index
  end

  # dashboard for employee
  namespace :employee do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    get '/show', to: 'users#show', as: :show
  end

  resources :receipts, only: :show do
    resources :receipt_items, only: [:new, :create]
  end
  resources :trips do
    get '/export', to: 'trips#export', as: :export
    resources :receipts, only: [:new, :update, :create]
  end
  resources :receipts, only: [:show, :edit, :destroy] do
    resources :receipt_items, except: [:index, :show, :destroy, :edit]
  end
  resources :receipt_items, only: [:destroy, :edit]
  get '/users/:id', to: 'users#show', as: :user_show

  #pdf generating routes
  get '/trips/:id/report', to: 'trips#report', as: :report
end

app/views/shared/_budget_bar.html.erb
<div class="budget-bar list">
  <div class="budget-empty">
    <p><%= number_to_currency(trip_budget.total_remaining, unit: "￥", separator: ",", precision: 0) %>/<%= number_to_currency(trip_budget.total_amount, unit: "￥", separator: ",", precision: 0) %> </p>
    <% if trip_budget.total_remaining.positive? %>
      <div class="opaque-budget" style="width: <%= trip_budget.budget_percent %>%"></div>
    <% else %>
      <div class="in-red"></div>
    <% end %>
  </div>
</div>

app/views/shared/_card-trip.html.erb
<div class="cards-list">

  <div class="card 1">
    <div class="card_image"> <img src="https://i.redd.it/b3esnz5ra34y.jpg" /> </div>
    <div class="card_title title-white">
      <p>Card Title</p>
    </div>
    </div>

  <div class="card 2">
    <div class="card_image">
      <img src="https://cdn.blackmilkclothing.com/media/wysiwyg/Wallpapers/PhoneWallpapers_FloralCoral.jpg" />
    </div>
    <div class="card_title title-white">
      <p>Card Title</p>
    </div>
  </div>

  <div class="card 3">
    <div class="card_image">
      <img src="https://media.giphy.com/media/10SvWCbt1ytWCc/giphy.gif" />
    </div>
    <div class="card_title">
      <p>Card Title</p>
    </div>
  </div>

  <div class="card 4">
    <div class="card_image">
      <img src="https://media.giphy.com/media/LwIyvaNcnzsD6/giphy.gif" />
    </div>
    <div class="card_title title-black">
      <p>Card Title</p>
    </div>
  </div>

</div>

app/views/shared/_employee_heading.html.erb
<div class='mobile-heading'>
  <div class="heading-text">
    <h4><%= current_user.current_trip.start_date.strftime("%m/%d/%y") %> &#8212;
 <%= current_user.current_trip.end_date.strftime("%m/%d/%y") %> </h4>
    <h2>visiting <%= current_trip.customer %></h2>
    <h4>in <%= current_trip.destination %></h4>
  </div>
  <div class="budget">
    <p class="budget-title">Remaining Budget</p>
    <div class="budget-bar heading">
      <div class="budget-empty">
        <p><%= number_to_currency(current_user.current_trip.total_remaining, unit: "￥", separator: ",", precision: 0) %>/<%= number_to_currency(current_user.current_trip.total_budget, unit: "￥", separator: ",", precision: 0) %> </p>
        <% if current_user.current_trip.total_remaining.positive? %>
          <div class="budget-percentage" style="width: <%= current_user.current_trip.budget_percent %>%"></div>
        <% else %>
          <div class="in-red"></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_employee_search.html.erb
<div class="mobile-cards">
  <%= form_tag employee_dashboard_path, method: :get do %>
    <div class="mobile-search text-center">
      <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Search trips"
                %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_floating_button.html.erb
<%= link_to new_trip_receipt_path(current_trip), class: "float halo" do %>
  <i class="fa fa-receipt my-float-receipt yellow">+</i>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-light-blue footer w-100">
  <div class="footer-links">
    <a href="https://github.com/AdilOmary" target="_blank"  title="Adil Omary" data-toggle="popover" data-trigger="hover" data-content="Project Manager"><%= image_tag "https://avatars1.githubusercontent.com/u/59479470?s=460&v=4", alt: "Adil's image", class: "avatar-bordered" %></a>
    <a href="https://github.com/rnd00" target="_blank" title="Ryanda Diedan" data-toggle="popover" data-trigger="hover" data-content="Lead Developer"><%= image_tag "https://avatars2.githubusercontent.com/u/42826652?s=460&v=4", alt: "Ryanda's image", class: "avatar-bordered" %></a>
    <a href="https://github.com/toadslop" target="_blank" title="Brian Heise" data-toggle="popover" data-trigger="hover" data-content="Back-end"><%= image_tag "https://avatars2.githubusercontent.com/u/31160338?s=460&v=4", alt: "Brian's image", class: "avatar-bordered" %></a>
    <a href="https://github.com/Gakkun89" target="_blank"title="Mike Warren" data-toggle="popover" data-trigger="hover" data-content="Front-end"><%= image_tag "https://avatars0.githubusercontent.com/u/28691463?s=460&v=4", alt: "Mike's image", class: "avatar-bordered" %></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon Tokyo by Team Bokkun
  </div>
</footer>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="d-flex justify-content-between w-100">
    <%= link_to employee_dashboard_path, class: "navbar-brand" do %>
      <h3>Bokkun</h3>
    <% end %>
    <%= link_to "#", id: "navbarDropdown", data: { toggle: "dropdown", target: '#navbarSupportedContent' }, 'aria-haspopup': true, 'aria-expanded': false, 'aria-label': 'navbarSupportedContent' do %>
      <% avatar = current_user.avatar.nil? ? 'https://res.cloudinary.com/kinzame-herokuapp-com/image/upload/v1583746668/placeholder/Missing_avatar_u1azml.svg' : current_user.avatar %>
      <%= image_tag avatar, class: "avatar", alt: "avatar-large", style: "border: 1px solid white; margin-right: 8px;" %>
    <% end %>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_side-bar.html.erb
<div class="navbar">
  <header class="main-head">
    <nav class="head-nav">
      <ul class="menu">
        <li class="justify-content-around">
          <%= link_to employer_dashboard_path do %>
            <div class="mx-3">
              <%= image_tag @current_user.avatar, class: "avatar", alt: "avatar-large" %>
            </div>
            <span id="user-name"><%= @current_user.first_name %> <%= @current_user.last_name %></span>
          <% end %>
        </li>
        <li class="justify-content-around">
          <%= link_to employer_dashboard_path do %>
            <div class="mx-3">
              <i class="fas fa-home fa-2x"></i>
            </div>
            <span class="">Dashboard</span>
          <% end %>
        </li>
        <li class="justify-content-around">
          <%= link_to trips_path do %>
            <div class="mx-3">
              <i class="fas fa-plane fa-2x"></i>
            </div>
            <span class="">Trips</span>
          <% end %>
        </li>
        <li class="justify-content-around">
          <%= link_to employer_index_path do %>
            <div class="mx-3">
              <i class="fas fa-user-friends fa-2x"></i>
            </div>
            <span class="">Employees</span>
          <% end %>
        </li>
        <li class="justify-content-around">
          <%= link_to destroy_user_session_path, method: :delete do %>
            <div class="mx-3">
              <i class="fas fa-sign-out-alt fa-2x"></i>
            </div>
            <span class="">Sign Out</span>
          <% end %>
        </li>
      </ul>
    </nav>
  </header>
  <div class="wrap-all-the-things"></div>
</div>