config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  #temporary testing route -- delete later
  get '/mobile', to: 'pages#mobile'
  get '/desktop', to: 'pages#desktop'

  # dashboard for employer
  namespace :employer do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    get '/show', to: 'users#show', as: :show
    get '/employees', to: 'users#index', as: :index
  end

  # dashboard for employee
  namespace :employee do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    get '/show', to: 'users#show', as: :show
  end

  resources :receipts, only: :show do
    resources :receipt_items, only: [:new, :create]
  end
  resources :trips do
    get '/export', to: 'trips#export', as: :export
    resources :receipts, only: [:new, :update, :create]
  end
  resources :receipts, only: [:show, :edit, :destroy] do
    resources :receipt_items, except: [:index, :show, :destroy, :edit]
  end
  resources :receipt_items, only: [:destroy, :edit]
  get '/users/:id', to: 'users#show', as: :user_show

  #pdf generating routes
  get '/trips/:id/report', to: 'trips#report', as: :report
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :receipts
  has_many :trip_users
  has_many :trips, through: :trip_users

  validates :first_name, :last_name, :job_title, presence: true
  validates :manager, inclusion: {in: [true, false]}

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def current_trip
    trip = self.trips.order(start_date: :desc).first
  end
end

app/controllers/employee/users_controller.rb
module Employee
  class UsersController < ApplicationController

    def dashboard
      @user = current_user
      @current_trip = @user.trips.order(start_date: :desc).first
      @query = params[:query]
      authorize @user
      if params[:query].present?
        @trips = Trip.search_all(params[:query])
      else
        @trips = @user.trips.order(start_date: :desc)
      end
    end

    def show
      @user = User.find_by(id: params[:id])
      authorize @user
    end

  end
end

app/controllers/employer/users_controller.rb
module Employer
  class UsersController < ApplicationController

    def dashboard
      @user = current_user
      authorize @user
    end

    def index
      @users = policy_scope(User)
    end

    def show
      @user = User.find_by(id: params[:id])
      authorize @user
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard
    @user = current_user
    @trips = @user.trips.order(start_date: :desc)
    authorize @user
  end

  def show
    @user = User.find_by(id: params[:id])
    authorize @user
  end
end

app/views/employer/users/dashboard.html.erb
<%= render 'shared/side-bar' %>
<div class="d-flex justify-content-center">
  <div class="width-200">
  </div>
  <div class="container employer-content">
    <div class="title m-3">
      <div class="title-text">
        <h1 class="m-auto">Dashboard</h1>
      </div>
      <div class="nav-btns">
        <%= link_to "Add a Trip", new_trip_path, class: "btn btn-approve w-30 m-auto"  %>
      </div>
    </div>
    <!-- linebreak -->
    <div class="w-100 border"></div>
    <!-- linebreak -->
    <div class="dash-container my-3 text-center justify-content-around">
      <div class="dash-stats m-3">
        <h3>Spending - 30 days</h3>
        <%= pie_chart( Trip.total_spend(30),
            colors: ['#AD5A5D', '#2A3347', '#EFC125', '#96B4C2'],
            prefix: '￥',
            thousands: ",",
            donut: true,
            legend: :bottom,
            library: { tooltips: { pieSliceText: 'value' } } ) %>
      </div>
      <div class="dash-stats m-3">
        <h3> Top 5 locations</h3>
        <% @location_spend = Trip.location_spend %>
        <%= column_chart( @location_spend,
            colors: ['#AD5A5D', '#2A3347', '#EFC125', '#96B4C2'],
            prefix: '￥',
            thousands: ",",
            legend: :bottom ) %>
      </div>
    </div>
    <!-- linebreak -->
    <div class="w-100 border"></div>
    <!-- linebreak -->
    <h2 class="my-3 text-center">Recent Trip</h2>
    <% if @user.current_trip.nil? %>
      <div class="row">
        <div class="col-md-12 p-3 my-3 text-md-center font-weight-bold">
          <h4>You don't have any trips right now!</h4>
        </div>
      </div>
    <% end %>
    <% unless @user.current_trip.nil? %>
      <div class="row justify-content-around">
        <!-- two col, one info, one chart -->
        <div class="col-md-3 p-3 my-3 border position-relative font-weight-bold text-md-center align-self-center" id="recent-trip-info" >
          <!-- destination, customer, date -->
          <div class="my-3">
            <h3 class="" id=""><%= @user.current_trip.customer %></h3>
            <h4 class="" id="destination"><%= @user.current_trip.destination %></h4>
            <h4 class="" id=""><%= @user.current_trip.start_date.strftime("%a, %d %b") %></h4>
          </div>
          <a class="stretched-link" href="/trips/<%= @user.current_trip.id %>" ></a>
        </div>
        <div class="col-md-8 p-3 my-3 border position-relative" id="recent-trip-chart">
          <!-- budgetbar start -->
          <div class="text-center font-weight-bold" id="dashboard-budgetbar">
            <h3>Remaining Budget</h3>
            <div class="budget-bar heading">
              <div class="budget-empty">
                <p><%= number_to_currency(@user.current_trip.total_remaining, unit: "￥", separator: ",", precision: 0) %>/<%= number_to_currency(@user.current_trip.total_budget, unit: "￥", separator: ",", precision: 0) %> </p>
                <% if @user.current_trip.total_remaining.positive? %>
                  <div class="budget-percentage" style="width: <%= @user.current_trip.budget_percent %>%"></div>
                <% else %>
                  <div class="in-red"></div>
                <% end %>
              </div>
            </div>
          </div>
          <!-- budgetbar end -->
          <div class="border w-100 my-3"></div>
          <!-- piechart barchart start -->
          <div class="text-center font-weight-bold" id="dashboard-barchart">
            <%= bar_chart( @user.current_trip.total_spend,
                colors: ['#AD5A5D', '#2A3347', '#EFC125', '#96B4C2'],
                prefix: '￥',
                thousands: ",",
                legend: false ) %>
          </div>
          <!-- piechart barchart end -->
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/employer/users/index.html.erb
<%= render 'shared/side-bar' %>
<div class="d-flex justify-content-center">
  <div class="width-200">
  </div>
  <div class="container employer-content">
    <h1 style="text-align:center;">Employee List</h1>
    <!-- linebreak -->
    <div class="w-100 border"></div>
    <!-- linebreak -->
    <% @users.each do |user| %>
      <div class="card-product my-3">
        <img src=<%= user.avatar %> >
        <div class="card-product-infos">
          <h2><%= link_to [user.first_name, user.last_name].join(" "), user_show_path(user) %></h2>
          <p><strong><%= "#{user.email}" %></strong></p>
          <p><%= user.job_title %> </p>
        </div>
      </div>
    <% end %>
  </div>
</div>