config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  #temporary testing route -- delete later
  get '/mobile', to: 'pages#mobile'
  get '/desktop', to: 'pages#desktop'

  # dashboard for employer
  namespace :employer do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    get '/show', to: 'users#show', as: :show
    get '/employees', to: 'users#index', as: :index
  end

  # dashboard for employee
  namespace :employee do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    get '/show', to: 'users#show', as: :show
  end

  resources :receipts, only: :show do
    resources :receipt_items, only: [:new, :create]
  end
  resources :trips do
    get '/export', to: 'trips#export', as: :export
    resources :receipts, only: [:new, :update, :create]
  end
  resources :receipts, only: [:show, :edit, :destroy] do
    resources :receipt_items, except: [:index, :show, :destroy, :edit]
  end
  resources :receipt_items, only: [:destroy, :edit]
  get '/users/:id', to: 'users#show', as: :user_show

  #pdf generating routes
  get '/trips/:id/report', to: 'trips#report', as: :report
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  has_many :receipt_items, dependent: :destroy
  belongs_to :user
  belongs_to :trip_budget
  has_one :trip, through: :trip_budget
  has_one :budget, through: :trip_budget
  has_one_attached :photo

  validates :company, :total_amount, :date, presence: true
  validates :total_amount, numericality: { only_integer: true }

  def category
    self.budget.name
  end

  def total_tax
    (self.receipt_items.reduce(0) { |total, item| total + (item.amount * (item.tax / 100.0 )) }).floor
  end

  def sub_total
    self.receipt_items.reduce(0) { |total, item| total + item.amount}
  end

  def total
    sub_total + total_tax
  end

  def all_items?
    self.total == self.total_amount
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def new
    @receipt = Receipt.new
    @trip = Trip.find_by(id: params[:trip_id])
    @receipt.trip = @trip
    @receipt.user = current_user
    authorize @receipt
  end

  def create
    @receipt = Receipt.new(receipt_params)
    @receipt.user = current_user
    @receipt.trip = Trip.find_by(id: params[:trip_id])
    authorize @receipt
    if @receipt.photo.attached?
      @lines = OCR.total("https://res.cloudinary.com/kinzame-herokuapp-com/image/upload/#{@receipt.photo.key}.jpg")
      @receipt.total_amount = OCR.total_amount(@lines) || 0
    else
      @receipt.total_amount = 0
    end
    if @receipt.save
      redirect_to receipt_path(@receipt)
    else
      render :new
    end
  end

  def show
    @receipt = Receipt.find_by(id: params[:id])
    @receipt_item = ReceiptItem.new
    authorize @receipt
  end

  def edit
    @receipt = Receipt.find_by(id: params[:id])
    @trip = @receipt.trip
    authorize @receipt
  end

  def update
    @receipt = Receipt.find_by(id: params[:id])
    authorize @receipt
    if @receipt.update(receipt_params)
      redirect_to receipt_path(@receipt)
    else
      render :edit
    end
  end

  def destroy
    @receipt = Receipt.find_by(id: params[:id])
    @receipt.destroy
    authorize @receipt
    if current_user.manager
      redirect_to employer_dashboard_path
    else
      redirect_to employee_dashboard_path
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_trip
    @trip = Trip.find(params[:trip_id])
  end

  def receipt_params
    params.require(:receipt).permit(:company, :total_amount, :date, :user_id, :category, :trip_budget_id, :photo)
  end
end

app/views/receipts/_employee_receipt_heading.html.erb
<div class='mobile-heading'>
  <div class="heading-text receipt">
    <h4><%= receipt.budget.name %> from <%= receipt.company %></h4>
    <div class="d-flex align-items-center justify-content-center">
      <h5>on <%= receipt.date.strftime("%B %d") %></h5>
      <%= link_to edit_receipt_path(@receipt) do %>
        <i class="fas fa-pencil-alt edit-button"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/receipts/_employee_receipt_index.html.erb
<div class="mobile-cards">
  <% current_trip.trip_budgets.each do |trip_budget| %>
    <button class="mobile-card" data-toggle="collapse" data-target="#a-<%= trip_budget.id %>" aria-expanded="false" aria-controls="<%= trip_budget.id %>">
      <h2 class='symbol'><%=raw trip_budget.budget.symbol %></h2>
      <%= render 'shared/budget_bar', trip_budget: trip_budget %>
    </button>
    <div class="collapse" id="a-<%= trip_budget.id%>">
      <div class="list-box mobile-card">
        <div class="push"></div>
          <div class="receipt-list">
            <div class="receipt-name">
              <% if trip_budget.receipts.empty? %>
                <p>No receipts entered.</p>
              <% else %>
                <% trip_budget.receipts.each do |receipt| %>
                    <%= link_to receipt_path(receipt), class: "receipt-line" do %>
                      <div><p><%= receipt.company %></p></div>
                      <div><p><%= number_to_currency(receipt.total, unit: "￥", separator: ",", precision: 0) %></p></div>
                    <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/receipts/_employee_receipt_item_list.html.erb
<div class="container center">
  <% if @receipt.receipt_items.empty? %>
    <div class="container" id="no-items">
      <p class="text-center">Enter the items from receipt.</p>
    </div>
  <% end %>
  <table>
    <thead id="receipt-table-head">
      <tr id="head-row" style="border-bottom: 3px solid black;">
        <th width="45%">Item</th>
        <th width="20%">Tax</th>
        <th width="25%">Price</th>
        <th width="15%"></th>
      </tr>
    </thead>
  </table>
  <div id="new-item-form">
    <%= render 'receipt_items/form', receipt: @receipt, receipt_item: @receipt_item %>
  </div>
  <table class="table table-hover receipt-table">
    <tbody id='receipt-table-body'>
      <% receipt.receipt_items.each do |item| %>
        <%= render 'receipt_items/row', item: item %>
      <% end %>
      <tr style="border-top: 2px solid black;">
        <td width="50%" style="text-align: right;"><b>Total tax: </b></td>
        <td width="20%"></td>
        <td id="receipt-total-tax" width="25%" style="text-align: right;"><%= number_to_currency(receipt.total_tax, unit: "￥", separator: ",", precision: 0) %></td>
        <td width="5%"></td>
      </tr>
      <tr>
        <td width="50%" style="text-align: right; border-top: none;"><b>Total: </b></td>
        <td width="45%" class="d-flex justify-content-end" style="border-top: none;" <%=raw 'style=color: red' if receipt.all_items? %>>
          <div id="receipt-total">
            <%= number_to_currency(receipt.total, unit: "￥", separator: ",", precision: 0) %>
          </div>
          <% unless receipt.total_amount == 0 %>
            <div class="d-flex">&nbsp;/ <%= number_to_currency(receipt.total_amount, unit: "￥", separator: ",", precision: 0) %>
            </div>
          <% end %>
        </td>
        <td width="5%" style="border-top: none;"></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/receipts/_employee_receipt_show.html.erb
<div class="mobile-wrapper">
  <%= render 'receipts/employee_receipt_heading', receipt: @receipt %>
  <% if @receipt.photo.attached? %>
    <div class="container receipt-container">
      <%= cl_image_tag @receipt.photo.key, effect: "trim:40" if @receipt.photo.attached? %>
    </div>
  <% else %>
    <%= simple_form_for [@receipt.trip, @receipt ], html: {class: "form-style form_submit_photo" } do |f| %>
      <div class="container mt-5">
        <p class="text-center">Please add a photo of the receipt.</p>
        <%= f.input :photo, label: false, as: :file, input_html: { id: :submit_photo } %>
      </div>
    <% end %>
  <% end %>
  <%= render 'receipts/employee_receipt_item_list', receipt: @receipt %>
  <%= link_to trip_path(@receipt.trip) do %>
    <div class="float-check disabled-halo" id="check-button">
      <i class="fas fa-check disabled-check"></i>
    </div>
  <% end %>
</div>

app/views/receipts/_employer_receipt_show.html.erb
<%= render 'shared/side-bar' %>
<div class="container employer-content">
  <h1 style="text-align:center;"><%= @receipt.company.titleize %> </h1>
  <div class="nav-btns d-flex justify-content-around">
    <%= link_to "Add a item", new_receipt_receipt_item_path(@receipt), class: "btn btn-approve w-30" %>
    <%= link_to "Edit this ticket", edit_receipt_path, class: "btn btn-approve w-30" %>
    <% if current_user.manager %>
      <%= link_to "Delete this ticket", receipt_path(@receipt), method: :delete, class: "btn btn-approve w-30" %>
    <% end %>
    <%= link_to "Go Back", trip_path(@receipt.trip), class: "btn btn-approve w-30" %>
  </div>

  <ul>
    <%= cl_image_tag @receipt.photo.key, height: 300, width: 400, crop: :fill if @receipt.photo.attached? %>
    <p>Company : <%= @receipt.company %></p>
    <p>Date : <%= @receipt.date %></p>
    <p>Total Amount : <%= @receipt.total_amount %></p>
    <p>Category : <%= @receipt.budget.name %></p>
  </ul>

  <ul>
    <h3>Items in this ticket</h3>
    <% if @receipt.receipt_items.nil? %>
      <p> No Items on this receipt Yet...</p>
    <% else %>
      <% @receipt.receipt_items.each do |item| %>
        <p>Name : <%= item.name %></p>
        <p>Amount : <%= item.amount %></p>
        <%= link_to edit_receipt_item_path(item) do %>
          <%= puts " " %>
          <div class="edit-button">
            <i class="fas fa-pencil-alt"></i>
          </div>
        <% end %>
        <%= link_to receipt_item_path(item), method: :delete do %>
          <div class="delete-button">
            <i class="fas fa-trash"></i>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/receipts/_form-edit.html.erb
<%= simple_form_for @receipt, html: {class: "form-style-9"} do |f| %>
  <%= f.input :company, label: "Purchased at" %>
  <%= f.input :date, as: :string, input_html: {class: "datepicker"}  %>
  <%= f.input :total_amount %>
  <%= f.association :trip_budget, collection: trip.trip_budgets, label_method: lambda {|trip_budget| "#{trip_budget.budget.name}"}, include_blank: false %>
  <%= f.input :photo, as: :file  %>
  <%= f.button :submit, class: "btn btn-approve w-30" %>
  <%= link_to "Go back", :back, class: "btn btn-approve w-30" %>
<% end %>

app/views/receipts/_form.html.erb
<%= simple_form_for [trip, receipt], html: {class: "form-style" } do |f| %>
  <%= f.input :company, label: "Purchased at" %>
  <%= f.input :total_amount, as: :hidden %>
  <div class="form-row">
    <div class="col-6">
      <%= f.input :date, as: :string, input_html: {class: "datepicker", value: Date.today} %>
    </div>
    <div class="col-6">
      <%= f.association :trip_budget, collection: trip.trip_budgets, label_method: lambda {|trip_budget| "#{trip_budget.budget.name}"}, include_blank: false %>
    </div>
  </div>
  <%= f.input :photo, as: :file  %>
  <%= button_tag type: :submit, class: "btn btn-approve w-30 submit-button", id:"submit-receipt" do %>
    Add the receipt
  <% end %>
  <div class="icon-back mx-auto">
    <%= link_to :back do %>
      <%= image_tag "left-arrow.png" %>
    <% end %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<%= render 'shared/side-bar' if current_user.manager %>
<div class="container <%=raw 'employer-content' if current_user.manager %>">
  <h1 style="text-align:center;">Edit a Receipt</h1>
  <%= render 'form', receipt: @receipt, trip: @trip%>
</div>

app/views/receipts/new.html.erb
<%= render 'shared/side-bar' if current_user.manager %>
<div class="container <%=raw 'employer-content' if current_user.manager %>">
  <h1 style="text-align:center;">New Receipt</h1>
  <%= render 'form', receipt: @receipt, trip: @trip %>
</div>

app/views/receipts/show.html.erb
<%= render current_user.manager ? 'receipts/employer_receipt_show' : 'receipts/employee_receipt_show' %>